### ISSUE TITLE
Wildcard match is not working

### ISSUE THREAD

**Issue by nachokb** [ankit/stylebot#346]
Styles containing wildcards are not shown at all in the extension's dropdown.

Examples:
- http://stylebot.me/styles/7004 (`*.slack.com`, `**.slack.com**`): nothing shows up on `https://xxyyzz.slack.com/messages/general`

![image](https://cloud.githubusercontent.com/assets/17967/4516262/9cf1b4bc-4bec-11e4-9bfa-266d69392962.png)
- http://stylebot.me/styles/4000 (`mail.google.com**`) does not show up either

**Comment by CrossfireCurt** [comment]
I'm experiencing something similar, but with the regex URL matching: ^(.*)git.domain.com(.*)merge_requests\/(.*)$

I'm trying to style the Merge Request page in a gitlab deployment. To do this I use a very specific regex to match the page. However, when I go to the page initially the style is not applied. I have to refresh for it to apply.

But that's not the big thing that bothers me... the real problem is that even if I navigate away from that URL to another page on the site, the style is still applied! I have to refresh that page for the style to be removed.
