### ISSUE TITLE
links lead to advertisement page

### ISSUE THREAD

**Issue by cgm707** [ankit/stylebot#433]
I clicked on many of the styles listed, and got directed to an advertisement page. Impossible to get to the styles!

**Comment by JonasNo** [comment]
You forgot to mention which site you are on.

**Comment by QuietusPlus** [comment]
See https://github.com/ankit/stylebot/issues/352

There has been an exploit in the comments section for ALMOST TWO YEARS. Someone injected their own code and has been getting advertising clicks for maybe even longer.

The developer seems to have been aware of this since July 2014, when his "Security Researcher" pointed it out to him: https://github.com/ankit/stylebot/issues/340

I DO NOT ADVISE you use this extension, who knows what else has been  ignored for almost two years.

**Comment by marcus-at-localhorst** [comment]
Somebody posted this `<meta http-equiv="refresh" content="0;URL=http://www.clixsense.com/?68706xxx">` in the comments of popular styles. This leads to the immediate redirect.
Unfortunately there seems to be no solution - maybe hitting ESC fast enough before the comment gets executed.

**Comment by JonasNo** [comment]
Last time I checked there is no support for meta tag interception in Chrome and I wouldn't hold my breath for that to come anytime soon. Have been requested for ages.
For problematic sites use the trusty good old Firefox with NoScript, Adblock Plus and NoRedirect add-ons. A replacement for Stylebot in Firefox is Stylish.
Good tip is to surf problematic urls in Private mode.
Just tested in Firefox the url in #352 and no redirect.
