### ISSUE TITLE
!important attribute?

### ISSUE THREAD

**Issue by Permannoyed** [ankit/stylebot#451]
Hi, I have found a site that is using the !important attribute on several div containers (with obtrusive ads in them). This is causing their attributes to override any custom css I put in. For example: I want to change the visibility of an element. So I use Stylebot to change that element's "display: block !important" attribute. I want to change it to "display: none". Which Stylebot does just fine.

Now comes the problem. Stylebot seems to be unable to add it's own "!important" tag so that my CSS isn't overridden. At least, every time I have tried to use it, the tag does not save into the custom css to be injected, and the element in question pops back up as soon as Stylebot is closed.

Please add support for this attribute as its absence in Stylebot allows it to be selectively used to prevent custom css from changing an attribute, defeating the whole point of your (awesome) extension.

Thanks!

**Comment by Fordi** [comment]
I think the fix would be to include the injected stylesheet at the end of the `head` tag, rather than at the start.

**Comment by geckoseo** [comment]
Stylebot appends the !important override to all of the rules it injects..

If it isn't working for some reason, it means your rule is not specific enough, or that the css being applied which won't go away is actually being injected after the page loads by means of javascript, in which case you can never override it unless you use ajax.

You can almost always override the other !important rules by prefixing your Stylebot rule with an additional class. One which makes your rule even more specific than the one it is meant to override.

In extreme cases, you could use the body tag as a prefix, or even the html tag. 

This practice makes page loading times even slower than is normal when using Stylebot on its own, because if a rule lower down includes !important, it forces the browser to parse the stylesheets again to find the most specific rule.
