### ISSUE TITLE
Feature request : disable styling temporalily

### ISSUE THREAD

**Issue by xurei** [ankit/stylebot#460]
Sometimes it is useful to disable Stylebot without actually removing the styling itself. It would be nice to have a menu item to do that.

**Comment by last-chance** [comment]
+1

This would be hugely useful for me. I use stylebot to hide unnecessary elements from ticket tracking systems at work, but every so often I need to glance at something I'm hiding. 

Normally removing and then re-adding the style isn't that hard, since I have it uploaded to the site, but since the site has been down, this has gotten insanely cumbersome. I'm just glad that I had my CSS saved elsewhere!

**Comment by AnEmortalKid** [comment]
@xurei 

Can you not go to Stylebot -> Options -> Styles and uncheck the custom style for that site?

**Comment by xurei** [comment]
That's what I'm doing now but a quicker way would be useful for my use cases.

**Comment by ankit** [comment]
This is now supported via the popup.
