### ISSUE TITLE
Alternative to StyleBot

### ISSUE THREAD

**Issue by NPC-112** [ankit/stylebot#467]
There is an alternative called [freestyler](http://freestyler.ws) that looks extremely similar, while being more touched up and offering more features on top of a site that is not down *and* not abandoned. 
Also has that wonderful feature to toggle styles without deleting them!

It's sad to say to jump ship, but if this extension was a foundation for freestyler then its at least worth a try. 

It also appears that the change in functionality/look that is almost an exact copy to this extension was recent. 
Now i'm wondering, is this OK? They don't appear to be open source. 
What do you think?

**Comment by jspreddy** [comment]
One issue I have with freestyler is that I can't create styles locally without putting them on their site.

**Comment by NPC-112** [comment]
Actually, you can. Opening up the editor, selecting an element, making changes, then closing the editor keeps the changes (at least for me).
It even persists across relaunching chrome. 

And when going back to where the style applies too, you can see it at the top of the extension's popup with a wrench button. under the wrench you can open the editor for it.

What I don't like about it is that the overview of installed/active styles can be accessed by clicking see all at the top, but it is handled by their site instead and not locally. There is also no chrome options page.

**Comment by ankit** [comment]
@NPC-112 I am sorry you have decided to switch. Unfortunately, i have very little time after my day job to maintain stylebot and reply to issues. I do plan to bring stylebot.me backup after making a few changes but it may take a while. Since this is a side project, I cannot really commit to a timeline and please adopt alternatives if you feel they work better. 

I am triaging stylebot issues and closing this one. Thank
