### ISSUE TITLE
can't use !important

### ISSUE THREAD

**Issue by aimbob** [ankit/stylebot#503]
can't use !important

**Comment by greena13** [comment]
Stylebot seems to automatically apply `!important` - are you sure you need to specify it in your case?

**Comment by taylorsmurphy** [comment]
This issue is perhaps due to the removal of the text "!important" from the CSS editor page. Upon save it is just gone. In certain situations this looks like it is not working properly. 

In a perfect world, adding "!important" to a style should trigger a popup notification that explains that it is redundant or whatever the reason is, and notifies the user that it will be erased from the stylesheet they just typed in

**Comment by fillspan** [comment]
It does not seem to be automatically applied to me... on the site www.standard.co.uk I'm trying to remove the overlay div.qc-cmp-ui-container (which adds a second scrollbar and won't let me highlight text. It disappears when you accept cookies). Opening the Chrome dev tool and adding "display: none" doesn't do anything, but with an added "!important" it disappears.

The same overlay won't let me interact with Stylebot either, so I have to remove it through the dev tool to access SB. But after adding a "display: none" to it in SB, it doesn't disappear.

**Comment by mattjmoney** [comment]
Would be helpful to have the option to turn off `!important` - for example with max-width it's not required.

**Comment by jeffvella** [comment]
+1

I need to specify !important to add a scrollbar to a page.

When I type this it works and the site shows the scrollbar on the page as expected.

`body {
    overflow: scroll !important;
}`

As soon as style bot saves it, it reverts to the following:

`body {
    overflow: scroll ;
}`

and the page no longer has a scrollbar.
