### ISSUE TITLE
Where can I setting global styles?

### ISSUE THREAD

**Issue by zenkarsha** [ankit/stylebot#543]
HI

The change log says in version 2.4 "Remove explicit Global Stylesheet setting in the options page", where can I enable it? I've try to use "*" as URI regex, but it overwrite site style when I open the sidebar editor. 🧐

**Comment by ankit** [comment]
@zenkarsha currently, it is a limitation of how things are implemented. when you open stylebot on a page, it merges all the styles applicable on the page and copies it into the most specific url / site style for the page. 

i am actively working a big new release and i will fix this issue in the release so that it does not overwrite the style of the site.

**Comment by quantumleap-** [comment]
The following keyboard shortcuts are used in stylebot Ver.2.2x (my personal mod ver)
 - Alt+Shift+S: toggle site style
 - Alt+Shift+A: toggle global style

I expect features like this to be implemented in official Ver.3.x

**Comment by ankit** [comment]
yes there will be a shortcut for toggling the site style for the current tab. however, i don't have a separate shortcut for the global style (but it would be easily toggle-able via the popup)

**Comment by quantumleap-** [comment]
@ankit Thank you for your reply. I'm looking forward to the release fo stylebot V3 :)

**Comment by ankit** [comment]
v3 is now out. the original issue where the style got overwritten should now be fixed and the toggle options in the popup will also be available (and toggle shortcut for site's style)
