### ISSUE TITLE
[Bug] When we select a font-family that's not on our computer, the import statement doesn't import true bolds and italics, and there's no way to configure it otherwise

### ISSUE THREAD

**Issue by saadrehman** [ankit/stylebot#573]
**Describe the bug**
When we select a font-family that's not installed on our computer, a google api important statement is inserted. However, that import statement only imports the one style and one face, resulting in faux bold and faux italics used throughout the page. Copying and pasting the import statement from Google Fonts site doesn't work, cause that supports css2 and Stylebot probably doesn't. 

**To Reproduce**
- https://hbr.org/2019/05/recruiting
- Click on style bot, and then the text div on the article
- Change font-family to "Merriweather" or any other serif font that's not installed, so observe the faux variations clearly.

**Expected behavior**
Either the import statement should already import all the variations (styles/weights) based on what's used on the page, or it should include them based on if I select that variation while configuring. Or it should allow the user to import them. 

**Screenshots**
![image](https://user-images.githubusercontent.com/338472/89496210-5dccde00-d7d3-11ea-8845-6eda21a5c9dc.png)
![image](https://user-images.githubusercontent.com/338472/89496241-6e7d5400-d7d3-11ea-9907-b33065929618.png)

**Comment by ankit** [comment]
Thanks for reporting @saadrehman. I think you found a couple of issues: 

> pasting the import statement from Google Fonts site doesn't work, cause that supports css2 and Stylebot probably doesn't. 

If you remove the quotes from the `@import` statement, it would work:

```
@import url(https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;500&display=swap)
```

I will fix the code so that it is able to parse `@import url('https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400&display=swap')` correctly. 

> Either the import statement should already import all the variations (styles/weights) based on what's used on the page or it should include them based on if I select that variation while configuring. 

This is a little non-trivial since I will have to look at the computed styles and the custom style for the selected elements, but I think it is feasible. I will attempt a fix for this too.

Thanks!

**Comment by ankit** [comment]
@saadrehman this should now be fixed in the latest update.
