### ISSUE TITLE
[Feature Request] Add a global stylesheet option

### ISSUE THREAD

**Issue by mabbas64** [ankit/stylebot#605]
**Is your feature request related to a problem? Please describe.**
There used to be a global stylesheet option in the old stylebot but I cannot find it anymore in the options. Would be nice to have an option like that as I use such rules to apply for multiple sites with similar layouts/structures.

**Describe the solution you'd like**
A way to add a single css rule that applies to all websites when the css selectors match e.g. a link with a unique class name on any site should be a particular color

**Comment by ankit** [comment]
@mabbas64 You can still add a global stylesheet if you set the URL to `*` in stylebot options. I removed the explicit Global Stylesheet option since it works similar to any regex based stylesheet (which can apply to multiple pages). But I can make the documentation better...

<img width="1262" alt="Screen Shot 2020-12-30 at 5 20 03 PM" src="https://user-images.githubusercontent.com/61857/103389380-58926780-4ac3-11eb-83f0-9eaa8e705ca3.png">
