### ISSUE TITLE
[Bug] The end of the style is covered by the scroll bar

### ISSUE THREAD

**Issue by Higurashi-kagome** [ankit/stylebot#629]
**Describe the bug**

The end of the style is covered by the scroll bar in some cases, causing can't click the end of the CSS line.

**To Reproduce**

It might not be an issue that can easily reproduce by steps. See the screenshot below, please.

**Expected behavior**

It should be easily jumping the cursor to the end by clicking the end of the line.

**Screenshots**

<details>
<summary>Details</summary>

![demo](https://user-images.githubusercontent.com/51501079/113813720-fff9f700-97a2-11eb-9f01-ecc1d8278dfa.gif)

</details>

**Comment by ankit** [comment]
@Higurashi-kagome i added support for resizing the editor + added additional space in the code editor, so it will be possible to mitigate this issue with more space (seems more related to the wrapping behavior in https://microsoft.github.io/monaco-editor/, i didn't really check if this is fixed in newer versions...). Wrapping is useful since we have limited space to write code, so keeping that behavior

**Comment by Higurashi-kagome** [comment]
@ankit Resizing might be helpful, I will test it in the future. I presume that it might be also considered to add a horizontal scroll bar, which would give users a chance to scroll to the end when got this issue.

**Comment by ankit** [comment]
Never mind, I was able to figure out a way to customize the wrapping behavior to avoid collision with the scrollbar. I also disabled the hover suggestions to reduce the noise.
